In [1]:
# NLP303 Assessment 3
#
# Detecting AI-generated Text
# Using Transformer-Based Classification
#
#
#
# Tibor Titusz Tarcsai - A00121308
#
# Jonathan Lim - A00142089
#
# Thomas Galindo Salazar - A00129258
#
#
#
# The purpose of this implementation is to demonstrate the building of a working protoype for a Classification task based on the Assessment 2 proposal.
#
#
#***********************
# HOW TO RUN THE CODE:
#***********************
#
# 1. - The notebook can run either in Jupyter Notebook or Google Colab 
#    - If using Google Colab, a Google Drive account is required for data access and storage.
#      Link for running on Colab: 
#
# 2. All helper functions are imported and loaded from the src folder
#
# 3. In Section [2], the "find_cat_dog_lion_tiger_folders" path finding function automatically locates the dataset folder,
#    so NO manual path configuration is required from the user.

In [2]:
# Environment Setup and Dependencies

In [2]:
!pip install -r ../requirements.txt
print("### Dependencies installed successfully ###")

Requirement already satisfied: transformers==4.52.4 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from -r ../requirements.txt (line 1)) (4.52.4)
Requirement already satisfied: torch in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from -r ../requirements.txt (line 2)) (2.6.0+cu124)
Requirement already satisfied: librosa==0.11.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from -r ../requirements.txt (line 3)) (0.11.0)
Requirement already satisfied: gdown==5.2.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from -r ../requirements.txt (line 4)) (5.2.0)
Requirement already satisfied: jiwer==4.0.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from -r ../requirements.txt (line 5)) (4.0.0)
Requirement already satisfied: ipywidgets in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from -r ../requirements.txt (line 6)) (8.1.8)
Requirement already satisfied: torchinfo in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from -r ../requirements.txt (line 7)) (1.8.0)
Requirement already satisfied: filelock in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from transformers==4.52.4->-r ../requirements.txt (line 1)) (3.29.4)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from transformers==4.52.4->-r ../requirements.txt (line 1)) (0.36.2)
Requirement already satisfied: numpy>=1.17 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from transformers==4.52.4->-r ../requirements.txt (line 1)) (2.4.6)
Requirement already satisfied: packaging>=20.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from transformers==4.52.4->-r ../requirements.txt (line 1)) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from transformers==4.52.4->-r ../requirements.txt (line 1)) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from transformers==4.52.4->-r ../requirements.txt (line 1)) (2026.6.28)
Requirement already satisfied: requests in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from transformers==4.52.4->-r ../requirements.txt (line 1)) (2.34.2)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from transformers==4.52.4->-r ../requirements.txt (line 1)) (0.21.4)
Requirement already satisfied: safetensors>=0.4.3 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from transformers==4.52.4->-r ../requirements.txt (line 1)) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from transformers==4.52.4->-r ../requirements.txt (line 1)) (4.68.3)
Requirement already satisfied: audioread>=2.1.9 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from librosa==0.11.0->-r ../requirements.txt (line 3)) (3.1.0)
Requirement already satisfied: numba>=0.51.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from librosa==0.11.0->-r ../requirements.txt (line 3)) (0.66.0)
Requirement already satisfied: scipy>=1.6.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from librosa==0.11.0->-r ../requirements.txt (line 3)) (1.18.0)
Requirement already satisfied: scikit-learn>=1.1.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from librosa==0.11.0->-r ../requirements.txt (line 3)) (1.9.0)
Requirement already satisfied: joblib>=1.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from librosa==0.11.0->-r ../requirements.txt (line 3)) (1.5.3)
Requirement already satisfied: decorator>=4.3.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from librosa==0.11.0->-r ../requirements.txt (line 3)) (5.3.1)
Requirement already satisfied: soundfile>=0.12.1 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from librosa==0.11.0->-r ../requirements.txt (line 3)) (0.14.0)
Requirement already satisfied: pooch>=1.1 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from librosa==0.11.0->-r ../requirements.txt (line 3)) (1.9.0)
Requirement already satisfied: soxr>=0.3.2 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from librosa==0.11.0->-r ../requirements.txt (line 3)) (1.1.0)
Requirement already satisfied: typing_extensions>=4.1.1 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from librosa==0.11.0->-r ../requirements.txt (line 3)) (4.15.0)
Requirement already satisfied: lazy_loader>=0.1 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from librosa==0.11.0->-r ../requirements.txt (line 3)) (0.5)
Requirement already satisfied: msgpack>=1.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from librosa==0.11.0->-r ../requirements.txt (line 3)) (1.2.1)
Requirement already satisfied: beautifulsoup4 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from gdown==5.2.0->-r ../requirements.txt (line 4)) (4.15.0)
Requirement already satisfied: click>=8.1.8 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from jiwer==4.0.0->-r ../requirements.txt (line 5)) (8.4.2)
Requirement already satisfied: rapidfuzz>=3.9.7 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from jiwer==4.0.0->-r ../requirements.txt (line 5)) (3.14.5)
Requirement already satisfied: fsspec>=2023.5.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.30.0->transformers==4.52.4->-r ../requirements.txt (line 1)) (2026.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from huggingface-hub<1.0,>=0.30.0->transformers==4.52.4->-r ../requirements.txt (line 1)) (1.5.1)
Requirement already satisfied: networkx in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from torch->-r ../requirements.txt (line 2)) (3.6.1)
Requirement already satisfied: jinja2 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from torch->-r ../requirements.txt (line 2)) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from torch->-r ../requirements.txt (line 2)) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from torch->-r ../requirements.txt (line 2)) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from torch->-r ../requirements.txt (line 2)) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from torch->-r ../requirements.txt (line 2)) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from torch->-r ../requirements.txt (line 2)) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from torch->-r ../requirements.txt (line 2)) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from torch->-r ../requirements.txt (line 2)) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from torch->-r ../requirements.txt (line 2)) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from torch->-r ../requirements.txt (line 2)) (12.3.1.170)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from torch->-r ../requirements.txt (line 2)) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from torch->-r ../requirements.txt (line 2)) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from torch->-r ../requirements.txt (line 2)) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from torch->-r ../requirements.txt (line 2)) (12.4.127)
Requirement already satisfied: triton==3.2.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from torch->-r ../requirements.txt (line 2)) (3.2.0)
Requirement already satisfied: setuptools in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from torch->-r ../requirements.txt (line 2)) (82.0.1)
Requirement already satisfied: sympy==1.13.1 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from torch->-r ../requirements.txt (line 2)) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from sympy==1.13.1->torch->-r ../requirements.txt (line 2)) (1.3.0)
Requirement already satisfied: comm>=0.1.3 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from ipywidgets->-r ../requirements.txt (line 6)) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from ipywidgets->-r ../requirements.txt (line 6)) (9.15.0)
Requirement already satisfied: traitlets>=4.3.1 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from ipywidgets->-r ../requirements.txt (line 6)) (5.15.1)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from ipywidgets->-r ../requirements.txt (line 6)) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from ipywidgets->-r ../requirements.txt (line 6)) (3.0.16)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets->-r ../requirements.txt (line 6)) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets->-r ../requirements.txt (line 6)) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets->-r ../requirements.txt (line 6)) (0.2.2)
Requirement already satisfied: pexpect>4.6 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets->-r ../requirements.txt (line 6)) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets->-r ../requirements.txt (line 6)) (3.0.52)
Requirement already satisfied: psutil>=7 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets->-r ../requirements.txt (line 6)) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets->-r ../requirements.txt (line 6)) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets->-r ../requirements.txt (line 6)) (0.6.3)
Requirement already satisfied: wcwidth in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets->-r ../requirements.txt (line 6)) (0.8.2)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from jedi>=0.18.2->ipython>=6.1.0->ipywidgets->-r ../requirements.txt (line 6)) (0.8.7)
Requirement already satisfied: llvmlite<0.49,>=0.48.0dev0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from numba>=0.51.0->librosa==0.11.0->-r ../requirements.txt (line 3)) (0.48.0)
Requirement already satisfied: ptyprocess>=0.5 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from pexpect>4.6->ipython>=6.1.0->ipywidgets->-r ../requirements.txt (line 6)) (0.7.0)
Requirement already satisfied: platformdirs>=2.5.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from pooch>=1.1->librosa==0.11.0->-r ../requirements.txt (line 3)) (4.10.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from requests->transformers==4.52.4->-r ../requirements.txt (line 1)) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from requests->transformers==4.52.4->-r ../requirements.txt (line 1)) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from requests->transformers==4.52.4->-r ../requirements.txt (line 1)) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from requests->transformers==4.52.4->-r ../requirements.txt (line 1)) (2026.6.17)
Requirement already satisfied: narwhals>=2.0.1 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from scikit-learn>=1.1.0->librosa==0.11.0->-r ../requirements.txt (line 3)) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from scikit-learn>=1.1.0->librosa==0.11.0->-r ../requirements.txt (line 3)) (3.6.0)
Requirement already satisfied: cffi>=1.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from soundfile>=0.12.1->librosa==0.11.0->-r ../requirements.txt (line 3)) (2.0.0)
Requirement already satisfied: pycparser in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from cffi>=1.0->soundfile>=0.12.1->librosa==0.11.0->-r ../requirements.txt (line 3)) (3.0)
Requirement already satisfied: executing>=1.2.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets->-r ../requirements.txt (line 6)) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets->-r ../requirements.txt (line 6)) (3.0.1)
Requirement already satisfied: pure_eval in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets->-r ../requirements.txt (line 6)) (0.2.3)
Requirement already satisfied: soupsieve>=1.6.1 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from beautifulsoup4->gdown==5.2.0->-r ../requirements.txt (line 4)) (2.8.4)
Requirement already satisfied: MarkupSafe>=2.0 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from jinja2->torch->-r ../requirements.txt (line 2)) (3.0.3)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /home/titus/miniconda3/envs/ai_text_detector/lib/python3.12/site-packages (from requests[socks]->gdown==5.2.0->-r ../requirements.txt (line 4)) (1.7.1)
### Dependencies installed successfully ###

In [1]:
# Initial Library Imports
# --------------------------------
# - torch for ... implementation
#
#
#
#
#

import os
import torch
import pandas as pd
import transformers


from torchinfo import summary
from transformers import pipeline

import sys
sys.path.append("../")


from src.downloader import DatasetDownloader

from src.datasetbuilder import DatasetBuilder

from src.preprocessing import TextPreprocessor

from transformers import AutoTokenizer, AutoModelForSequenceClassification

In [2]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using device: {device}")

Using device: cuda

# Section 1 - Load Dataset

In [4]:
# Initialises the downloader class
downloader = DatasetDownloader()

# Downloads raw datasets from google drive
print("### Downloading Dataset from Google Drive... ###")
downloader.start_downloading_dataset()

### Downloading Dataset from Google Drive... ###

Downloading...
From: https://drive.google.com/uc?id=16hDeETXMq4-o67YSqguDk6OC3VvXW7U7
To: /home/titus/projects/roberta-ai-text-detector/data/ai_written_humanised_v3_last2500.csv
100%|██████████| 6.47M/6.47M [00:01<00:00, 5.25MB/s]
Downloading...
From: https://drive.google.com/uc?id=1cAL9qHhyYIVnR0kxMBlzRFFyrZqiCf6O
To: /home/titus/projects/roberta-ai-text-detector/data/HUMAN_written_then_AI_polished_v3_last2500.csv
100%|██████████| 8.57M/8.57M [00:01<00:00, 5.54MB/s]
Downloading...
From: https://drive.google.com/uc?id=1LlTrJ6wdRkctvpT21O_XkNTfrHOBhX6L
To: /home/titus/projects/roberta-ai-text-detector/data/ai_generated_v2_last2500.csv
100%|██████████| 5.04M/5.04M [00:02<00:00, 1.82MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Meg3aFojjCGefepim0zVsArmze_5ttGy
To: /home/titus/projects/roberta-ai-text-detector/data/human_written_v2_last2500.csv
100%|██████████| 4.10M/4.10M [00:00<00:00, 5.02MB/s]

In [2]:
# Restructures datasets


raw_dataset_paths = [
            {
                "path": "../data/human_written_v2_last2500.csv"
            },
            {
                "path": "../data/ai_generated_v2_last2500.csv"
            },
            {
                "path": "../data/HUMAN_written_then_AI_polished_v3_last2500.csv"
            },
            {
                "path": "../data/ai_written_humanised_v3_last2500.csv"
            },
        ]


builder = DatasetBuilder()

raw_dataset = builder.build_dataset(
    raw_dataset_paths[0]["path"],
    raw_dataset_paths[1]["path"],
    raw_dataset_paths[2]["path"],
    raw_dataset_paths[3]["path"],
)

In [3]:
print(len(raw_dataset))

10000

In [27]:
raw_dataset.iloc[5049].text

'The middle-levels graph $M_k$ ($0<k\\in\\mathbb{Z}$) has a dihedral quotient pseudograph $R_k$ whose vertices are the $k$-edge ordered trees $T$, each $T$ encoded as a $(2k+1)$-string $F(T)$ formed via $\\rightarrow$DFS by: (i) ($\\leftarrow$BFS-assigned) Kierstead-Trotter lexical colors $0,\\ldots,k$ for the descending nodes; (ii) asterisks $*$ for the $k$ ascending edges. Two ways of corresponding a restricted-growth $k$-string $\\alpha$ to each $T$ exist, namely one Stanley\'s way and a novel way that assigns $F(T)$ to $\\alpha$ via nested substring-swaps. These swaps permit to sort $V(R_k)$ as an ordered tree that allows a lexical visualization of $M_k$ as well as the Hamilton cycles of $M_k$ constructed by P. Gregor, T. M\\"utze and J. Nummenpalo.'

In [ ]:
# Selects rows (delete rows: 5049 )
raw_dataset.iloc[5100:5150]

,text,label,label_name,cleaned_text
5100,The board of Indian conglomerate Reliance has ...,2,human_written_ai_polished,The board of Indian conglomerate Reliance has ...
5101,"In the middle of the night, fifteen-year-old G...",2,human_written_ai_polished,"In the middle of the night, fifteen-year-old G..."
5102,Image segmentation is an important component o...,2,human_written_ai_polished,Image segmentation is an important component o...
5103,European cross-country champion Hayley Yelling...,2,human_written_ai_polished,European cross-country champion Hayley Yelling...
5104,Here Be Dragons (1985) is the first of Penman’...,2,human_written_ai_polished,Here Be Dragons (1985) is the first of Penman’...
5105,"Young book fans have voted Fergus Crane, a sto...",2,human_written_ai_polished,"Young book fans have voted Fergus Crane, a sto..."
5106,"In this novel, Mia must learn to deal with pub...",2,human_written_ai_polished,"In this novel, Mia must learn to deal with pub..."
5107,Semantic segmentation of fine-resolution urban...,2,human_written_ai_polished,Semantic segmentation of fine-resolution urban...
5108,## Hodgson Speaks Out on Winter Break and Cha...,2,human_written_ai_polished,Hodgson Speaks Out on Winter Break and Champi...
5109,The novel was written in 1914. It is set a few...,2,human_written_ai_polished,The novel was written in 1914. It is set a few...
5110,This is a fascinating synopsis! You've capture...,2,human_written_ai_polished,This is a fascinating synopsis! You've capture...
5111,A book about the evolution of mutants and the ...,2,human_written_ai_polished,A book about the evolution of mutants and the ...
5112,This is a great summary of the plot from the *...,2,human_written_ai_polished,This is a great summary of the plot from the A...
5113,The novel tells the story of how an 11-year-ol...,2,human_written_ai_polished,The novel tells the story of how an 11-year-ol...
5114,Lenny is a recently released ex-convict. Despi...,2,human_written_ai_polished,Lenny is a recently released ex-convict. Despi...
5115,We study Brown measures of certain non-hermiti...,2,human_written_ai_polished,We study Brown measures of certain non-hermiti...
5116,In order to tackle the development of concurre...,2,human_written_ai_polished,In order to tackle the development of concurre...
5117,This is a fantastic synopsis! You've captured ...,2,human_written_ai_polished,This is a fantastic synopsis! You've captured ...
5118,## DRM Systems: A Complex Ecosystem of Fragme...,2,human_written_ai_polished,DRM Systems: A Complex Ecosystem of Fragmenta...
5119,The US budget deficit is set to hit a worse-th...,2,human_written_ai_polished,The US budget deficit is set to hit a worse-th...
5120,Legacy is the immediate sequel to Beguilement ...,2,human_written_ai_polished,Legacy is the immediate sequel to Beguilement ...
5121,"Manchester City's Paul Bosvelt will find out ""...",2,human_written_ai_polished,"Manchester City's Paul Bosvelt will find out ""..."
5122,"Some 2,000 jobs at MG Rover's Midlands plant m...",2,human_written_ai_polished,"Some 2,000 jobs at MG Rover's Midlands plant m..."
5123,The current flow of high accuracy astrophysica...,2,human_written_ai_polished,The current flow of high accuracy astrophysica...
5124,The growing popularity of online gaming could ...,2,human_written_ai_polished,The growing popularity of online gaming could ...
5125,"Jacob Ericson is a shy, enigmatic, and somewha...",2,human_written_ai_polished,"Jacob Ericson is a shy, enigmatic, and somewha..."
5126,The story is set in 18th century Japan and fea...,2,human_written_ai_polished,The story is set in 18th century Japan and fea...
5127,This sounds like a hilarious and darkly comedi...,2,human_written_ai_polished,This sounds like a hilarious and darkly comedi...
5128,This paper develops a method to carry out the ...,2,human_written_ai_polished,This paper develops a method to carry out the ...
5129,Graded posets frequently arise throughout comb...,2,human_written_ai_polished,Graded posets frequently arise throughout comb...
5130,Kostas Kenteris' lawyer has called for the dop...,2,human_written_ai_polished,Kostas Kenteris' lawyer has called for the dop...
5131,The novel provides an insight into the naval c...,2,human_written_ai_polished,The novel provides an insight into the naval c...
5132,This article discusses the growing market of *...,2,human_written_ai_polished,This article discusses the growing market of c...
5133,Boolean operations of geometric models are an ...,2,human_written_ai_polished,Boolean operations of geometric models are an ...
5134,This passage offers a fascinating analysis of ...,2,human_written_ai_polished,This passage offers a fascinating analysis of ...
5135,Jennifer Capriati has become the third leading...,2,human_written_ai_polished,Jennifer Capriati has become the third leading...
5136,Spectators were evacuated from Real Madrid's B...,2,human_written_ai_polished,Spectators were evacuated from Real Madrid's B...
5137,Let A be a commutative domain containing Z whi...,2,human_written_ai_polished,Let A be a commutative domain containing Z whi...
5138,This article provides a detailed analysis of t...,2,human_written_ai_polished,This article provides a detailed analysis of t...
5139,Belgian brewing giant Inbev has seen its profi...,2,human_written_ai_polished,Belgian brewing giant Inbev has seen its profi...
5140,The isothermal entropy change and adiabatic te...,2,human_written_ai_polished,The isothermal entropy change and adiabatic te...
5141,The US created fewer jobs than expected in Jan...,2,human_written_ai_polished,The US created fewer jobs than expected in Jan...
5142,The collection tells the story of a merchant f...,2,human_written_ai_polished,The collection tells the story of a merchant f...
5143,Eight people of varied backgrounds meet in the...,2,human_written_ai_polished,Eight people of varied backgrounds meet in the...
5144,"Crusade, like Brethren before it, follows Will...",2,human_written_ai_polished,"Crusade, like Brethren before it, follows Will..."
5145,This is a great summary of the football match!...,2,human_written_ai_polished,This is a great summary of the football match!...
5146,"Within this thesis, we propose a platform for ...",2,human_written_ai_polished,"Within this thesis, we propose a platform for ..."
5147,Kenya’s athletics body has reversed a ban on m...,2,human_written_ai_polished,Kenya’s athletics body has reversed a ban on m...
5148,The Kingdom of Semma is on the verge of war bu...,2,human_written_ai_polished,The Kingdom of Semma is on the verge of war bu...
5149,The book tells the story of a kindly and elder...,2,human_written_ai_polished,The book tells the story of a kindly and elder...

# Section 2 - Text Preprocessing

In [18]:
# Drops rows where 'text' is missing
raw_dataset = raw_dataset.dropna(subset=["text"]).reset_index(drop=True)

print(len(raw_dataset))

9993

In [19]:
text_preprocessor = TextPreprocessor()

raw_dataset["cleaned_text"] = raw_dataset["text"].apply(text_preprocessor.clean_text)



print(raw_dataset[["cleaned_text", "text"]].head(2))

                                        cleaned_text  \
0  For the first time in nearly 3 years i can fin...
1  Donnie Yen is a long time favorite of mine, al...

                                                text
0  For the first time in nearly 3 years i can fin...
1  Donnie Yen is a long time favorite of mine, al...

In [ ]:
# give it label 0
df_pure_human = pd.read_csv("../data/human_written_v2_last2500.csv")
df_pure_human.head(2)

,id,adv_source_id,source_id,model,decoding,repetition_penalty,attack,domain,title,prompt,generation
0,0a2c0b33-e74c-4e64-8926-6c79e6170728,0a2c0b33-e74c-4e64-8926-6c79e6170728,0a2c0b33-e74c-4e64-8926-6c79e6170728,human,NaN,NaN,none,reviews,Horrible Bosses,NaN,For the first time in nearly 3 years i can fin...
1,ce4c7569-283a-44fc-83f3-dc06b58c7796,ce4c7569-283a-44fc-83f3-dc06b58c7796,ce4c7569-283a-44fc-83f3-dc06b58c7796,human,NaN,NaN,none,reviews,Ip Man,NaN,"Donnie Yen is a long time favorite of mine, al..."

In [ ]:
# give it label 1
df_pure_ai = pd.read_csv("../data/ai_generated_v2_last2500.csv")
df_pure_ai.head(2)

In [ ]:
df_ai_polished = pd.read_csv("../data/HUMAN_written_then_AI_polished_v3_last2500.csv")
df_ai_polished.head(2)

,id,original_text,rewritten_text,label
0,3811d5e2-3513-49aa-883a-01f847a08c58,GlaxoSmithKline saw its profits fall 9% last y...,GlaxoSmithKline saw its profits fall 9% last y...,2
1,34ee9b7d-d7c9-446f-8c4e-9af9f8bdabf5,"Over the last two decades, deep learning has t...","Over the last two decades, deep learning has t...",2

In [23]:
df_humanised= pd.read_csv("../data/ai_written_humanised_v2.csv")
df_humanised.head(10)

,id,original_text,rewritten_text,label
0,7c168a1f-e4de-4358-b541-1ef7f09651c9,Incorporating Fully Transformed FST into Spars...,This research explores how to improve video-ba...,3
1,d42147ee-420d-481c-91a4-cbef4e789cf8,Abstract: The purpose of this work is to study...,The research presented aims to explore the str...,3
2,525293df-3281-4db8-bd8e-e63a44719b11,An important result in the study of homogeneou...,This study explores the fascinating relationsh...,3
3,5baa1082-0489-4364-9552-e10e7868cede,"In this paper, we present a characterization o...",This paper examines decidable separability for...,3
4,13eabe6e-eb83-461a-909e-fed1b569fdaf,Data compression algorithms have become increa...,My research focuses on studying data compressi...,3
5,ea0add69-e90a-421d-ba19-8217b8c91bfc,The nesting behavior of statistical mechanical...,This study focused on the nested loops problem...,3
6,d69b9054-bef2-409f-bd93-d2c8ff4f6469,An array of antennas could generate very large...,"The use of arrays for directional antennas, wh...",3
7,10749039-0913-449e-b7cd-ae4014af1f53,Adrenaline signaling is an integral part of hu...,The role of adrenaline in human behavior is we...,3
8,8f1a10b7-75a1-43a5-96ee-3f81c6dd8140,This paper investigates the properties of free...,Free ω-continuous and regular ordered algebras...,3
9,a8acd884-8533-479b-98f8-21584986d5a3,Abstract The purpose of this study was to iden...,Examining multiple linear regression datasets ...,3

In [25]:
df_humanised.iloc[8].original_text

'This paper investigates the properties of free ω-continuous and regular ordered algebras. We begin by providing a brief overview of these algebra structures, emphasizing their significance in mathematical logic and semantics. Our main result shows that the class of free ω-continuous orderedalgebras is not closed under taking subdirect products with abelian groups, while theclass of free regularorderedalgebrasisclosedundertakingsubdirectproductswithabeliangroups.Wealsoprovideanexplicitdescriptionofthefreeω-continuousandregularorderedalgebraonanorderedsetofsizeω1.Our findings contribute to the understanding of these algebras and may have implicationsfor other areas of mathematics and computer science.'

In [ ]:
# Section 3 - Tokenisation (BPE)

In [ ]:
# Section 4 - Load Pre-trained RoBERTa

In [ ]:
# Section 5- Fine-tuning

In [ ]:
# Section 6 - Model Inference

In [ ]:
# Section 7 - Threshold Classification

In [ ]:
# Section 8 - Evaluation

In [ ]:
# Section 9 - Visualisations

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("roberta-base")

model = AutoModelForSequenceClassification.from_pretrained(
    "fakespot-ai/roberta-base-ai-text-detection-v1"
)

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [ ]:
# Prints model summary
summary(model, input_size=(1, 512), dtypes=[torch.long])

==============================================================================================================
Layer (type:depth-idx)                                       Output Shape              Param #
==============================================================================================================
RobertaForSequenceClassification                             [1, 2]                    --
├─RobertaModel: 1-1                                          [1, 512, 768]             --
│    └─RobertaEmbeddings: 2-1                                [1, 512, 768]             --
│    │    └─Embedding: 3-1                                   [1, 512, 768]             38,603,520
│    │    └─Embedding: 3-2                                   [1, 512, 768]             768
│    │    └─Embedding: 3-3                                   [1, 512, 768]             394,752
│    │    └─LayerNorm: 3-4                                   [1, 512, 768]             1,536
│    │    └─Dropout: 3-5                                     [1, 512, 768]             --
│    └─RobertaEncoder: 2-2                                   [1, 512, 768]             --
│    │    └─ModuleList: 3-6                                  --                        85,054,464
├─RobertaClassificationHead: 1-2                             [1, 2]                    --
│    └─Dropout: 2-3                                          [1, 768]                  --
│    └─Linear: 2-4                                           [1, 768]                  590,592
│    └─Dropout: 2-5                                          [1, 768]                  --
│    └─Linear: 2-6                                           [1, 2]                    1,538
==============================================================================================================
Total params: 124,647,170
Trainable params: 124,647,170
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 124.65
==============================================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 427.83
Params size (MB): 498.59
Estimated Total Size (MB): 926.42
==============================================================================================================

In [ ]:
df = pd.read_csv("data/HUMAN_written_then_AI_polished.csv")

In [ ]:
print(df.head(200))

                                      id  \
0   e5e058ce-be2b-459d-af36-32532aaba5ff
1   f95b107b-d176-4af5-90f7-4d0bb20caf93
2   856d8972-9e3d-4544-babc-0fe16f21e04d
3   fbc8a5ea-90fa-47b8-8fa7-73dd954f1524
4   72c41b8d-0069-4886-b734-a4000ffca286
5   72fe360b-cce6-4daf-b66a-1d778f5964f8
6   df594cf4-9a0c-4488-bcb3-68f41e2d5a16
7   853c0e51-7dd5-4bb5-8286-e4aa8820173b
8   1649f195-8f98-4c79-92b6-54a5ca9261fa
9   5e23ab14-b85f-48e8-9aa3-15452e73524e
10  ddcb207c-a790-4e16-a053-4aced58d7c15
11  b00bf7dc-4de9-4ab4-9962-a16e0b5f4628
12  04d3809c-0abe-4bee-b1d2-9787af95362f
13  06bffeb2-bea0-4b0b-b60d-767ba9b660a7
14  5eb88a59-eb5a-49ea-8304-f67efe338921
15  1389aa64-25fb-4e56-9358-ef34143bfea9
16  d0064195-c22e-4550-a265-6b372deea3e0
17  417afaa2-2d21-4df1-953b-768647de9980
18  ce898c28-428f-446f-975e-a1265942f2da
19  380cd71d-3300-422c-9cde-8a63e71f2797
20  c093400c-2bd2-4e0d-a732-f99d499d58a9
21  05f40b6d-67cf-4a6e-ad2f-cfe003b7917e
22  c404dbd3-7cec-41f5-8b70-968e9212ed7c
23  bc43fe33-d378-4bc3-b666-038cbacbdbc8
24  eff4a017-daa1-4b5d-84ac-927333aaa900

                                        original_text  \
0   The recent advancements in artificial intellig...
1   High-quality training data play a key role in ...
2   The success of deep learning methods in medica...
3   Simultaneous segmentation of multiple organs f...
4   Detection faults in seismic data is a crucial ...
5   Image segmentation is often ambiguous at the l...
6   This paper studies the context aggregation pro...
7   We investigate Referring Image Segmentation (R...
8   In this work, we address the challenging task ...
9   Semantic segmentation of medical images is an ...
10  While improving prediction accuracy has been t...
11  Deep learning has not been routinely employed ...
12  We introduce a method that allows to automatic...
13  The balance between high accuracy and high spe...
14  The segmentation of medical images is a fundam...
15  The reliability of Deep Learning systems depen...
16  Semi-supervised learning has attracted great a...
17  A strong visual object tracker nowadays relies...
18  We introduce $\textit{InExtremIS}$, a weakly s...
19  Semantic, instance, and panoptic segmentations...
20  Fully convolutional U-shaped neural networks h...
21  Semantic segmentation from very fine resolutio...
22  Many approaches to 3D image segmentation are b...
23  Accurate segmentation of medical images into a...
24  This paper reports a CPU-level real-time stere...

                                       rewritten_text  label
0   The recent advancements in artificial intellig...      3
1   High-quality training data play a key role in ...      3
2   The success of deep learning methods in medica...      3
3   Simultaneous segmentation of multiple organs f...      3
4   Detection faults in seismic data is a crucial ...      3
5   Image segmentation is often ambiguous at the l...      3
6   The context aggregation problem in semantic im...      3
7   We investigate Referring Image Segmentation (R...      3
8   In this work, we address the challenging task ...      3
9   Semantic segmentation of medical images is an ...      3
10  Improving prediction accuracy has been the foc...      3
11  Deep learning has not been routinely employed ...      3
12  We introduce a method that allows for the auto...      3
13  The balance between high accuracy and high spe...      3
14  The segmentation of medical images is a fundam...      3
15  The reliability of Deep Learning systems depen...      3
16  Semi-supervised learning has attracted great a...      3
17  A strong visual object tracker nowadays relies...      3
18  We introduce $\textit{InExtremIS}$, a weakly s...      3
19  Semantic, instance, and panoptic segmentations...      3
20  Fully convolutional U-shaped neural networks h...      3
21  Semantic segmentation from very fine resolutio...      3
22  Many approaches to 3D image segmentation are b...      3
23  Accurate segmentation of medical images into a...      3
24  The paper reports a CPU-level real-time stereo...      3